#!/usr/bin/env bash

# docker build --tag east-empty \
# 	--build-arg "USER=$(whoami)" \
# 	--build-arg "host_uid=$(id -u)" \
# 	.

docker build --tag east-after-sys-setup \
	--build-arg "USER=$(whoami)" \
	--build-arg "host_uid=$(id -u)" \
	-f Dockerfile_after_sys_setup \
	.
