name: Label PR
on:
  pull_request:
    types: [opened]
permissions:
  contents: read
jobs:
  pr-labeler:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v5.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/pr-labeler.yaml
